apiVersion: apps/v1
kind: Deployment
metadata:
  name: intellmeet-redis
  labels:
    app.kubernetes.io/name: intellmeet-redis
    app.kubernetes.io/component: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intellmeet-redis
  template:
    metadata:
      labels:
        app: intellmeet-redis
        app.kubernetes.io/component: cache
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: intellmeet-redis-service
  labels:
    app.kubernetes.io/name: intellmeet-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: intellmeet-redis
