apiVersion: v1
kind: Secret
metadata:
  name: intellmeet-secret
  labels:
    app.kubernetes.io/name: intellmeet
    app.kubernetes.io/part-of: intellmeet
type: Opaque
stringData:
  MONGOOSE_KEY: "mongodb://intellmeet-mongodb-service:27017/intellmeet"
  JWT_SECRET_KEY: "intellmeet_jwt_secret_production_2026"
  JWT_REFRESH_SECRET: "intellmeet_refresh_secret_production_2026"
