apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "intellmeet.fullname" . }}-configmap
  labels:
    {{- include "intellmeet.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.config.port | quote }}
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}
  CLIENT_URL: {{ .Values.config.clientUrl | quote }}
  NODE_ENV: {{ .Values.global.environment | quote }}
