apiVersion: v1
kind: Service
metadata:
  name: {{ include "intellmeet.fullname" . }}-frontend-service
  labels:
    {{- include "intellmeet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
  selector:
    app: {{ include "intellmeet.fullname" . }}-frontend
