apiVersion: v1
kind: Secret
metadata:
  name: {{ include "intellmeet.fullname" . }}-secret
  labels:
    {{- include "intellmeet.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGOOSE_KEY: {{ .Values.secrets.mongooseKey | quote }}
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey | quote }}
  JWT_REFRESH_SECRET: {{ .Values.secrets.jwtRefreshSecret | quote }}
